name: Deploy Nest.js

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the Nest.js application
        run: npm run build

      - name: Check if secrets are available (for debugging)
        run: |
          echo "HOST: ${{ secrets.HOST }}"
          echo "USERNAME: ${{ secrets.USERNAME }}"
          echo "SSH_KEY: (masked for security)" # GitHub will automatically mask secrets here

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/test-nestjs
            git pull origin main
            npm install
            npm run build
            pm2 restart nestjs
